### ISSUE TITLE
Please enable option to input custom coins and add these ones

### ISSUE THREAD

**Issue by Gitbluelight** [mayaleh/Maya.CryptoFiatPrice#1]
Please add these popular coins: solana, fetchai, doge, GRT, uniswap.
Would be nice we can input the coins we want inside the app instead the developer has to do it.
Nice app, thanks!

**Comment by mayaleh** [comment]
Hello, 
Thank you for your interest in my widget for my Garmin watch and for suggesting additional features. While I appreciate your feedback, I must kindly decline your request to add support for other cryptocurrencies such as Solana, Fetch.ai, Dogecoin, GRT, and Uniswap.

My focus is specifically centered around Bitcoin, and I developed this app with that in mind. Unfortunately, I don't have the time or interest to expand its functionality to include other coins.

However, I encourage you to explore the option of forking the code and creating your own version of the app to support the coins you're interested in. The code is open source and free from any license restrictions, so you're welcome to adapt it as needed.

Best regards,
Mayaleh
